Repository ChromeGaming/Dot-Box, pull requests merged in 2024-07, with the labels that each got.

#436 Added Navbar in About US Page
  about.css
  about.html
Labels: gssoc, level1

#441 Sound Button Label Corrected in Game
  game.html
Labels: gssoc, level1

#450 added back button to game.html and FAQ page
  pages/FAQs.html
  pages/about.html
  pages/game.html
  styles/about.css
  styles/index.style.css
Labels: gssoc, level2

#451 Added a button to redirect to home after The game ends
  js/game.js
  pages/game.html
  styles/game.style.css
Labels: gssoc, level2

#457 Lets go page opens in the new page
  index.html
Labels: gssoc, level1

#464 FAQ page dropdown behaviour fixed
  js/FAQs.js
  pages/FAQs.html
Labels: gssoc, level2

#465 Music button label corrected
  index.html
Labels: gssoc, level1

#469 Fix Misaligned Elements on Small Screens
  pages/404.html
  styles/index.style.css
  styles/mainstyle.css
Labels: gssoc, level2

#468 Fixed: The Feedback is Overlapping Navbar and Footer
  index.html
Labels: gssoc, level2

#474 Added Cursor Trail Effect To The Website
  index.html
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/privacypolicy.html
  pages/termsofservice.html
  styles/index.style.css
  trail.js
Labels: gssoc, level2

#475 Theme change
  assets/videos/1.mp4
  index.html
  js/game.js
  js/index.js
  pages/game.html
  styles/game.style.css
  styles/mainstyle.css
Labels: gssoc, level3

#489 Added Reset Functionality and Thank You Pop Message After Submitting
  index.html
  styles/mainstyle.css
Labels: gssoc, level2

#491 Made the FAQ Page "Responsive" and Enhanced "Back to Home" Button
  pages/FAQs.html
  styles/FAQs.css
Labels: gssoc, level2

#492 Made "Privacy Policy, and Terms of services" Pages Responsive
  styles/privacypolicy.css
  styles/termsofservice.css
Labels: gssoc, level2

#493 ✔️Added Cursor-Trail Effect in All the Pages.
  index.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#495 ✔️ Resolved Music On/Off Button Issue!
  index.html
Labels: gssoc, level2

#507 Made The Feedback Form "Responsive" #494
  index.html
Labels: gssoc, level2

#511 Added cd Dot-Box
  README.md
Labels: gssoc, level1

#506 Added Licensing Page Reflecting MIT License
  index.html
  pages/licensing.html
  styles/licensing.css
Labels: gssoc, level2

#516 "Enhanced the Game Interface" and Added "Reset Functionality" and "Aligned Buttons" with Icons
  pages/game.html
Labels: gssoc, level2

#521 Modified the abot page's footer
  pages/about.html
  styles/about.css
Labels: gssoc, level2

#524 ✔️Resolved: "Contributors" Page is Working Issue
  pages/contributors.html
Labels: gssoc, level2

#505 Fixed and Enhance Working of The Cursor Trail Effect
  index.html
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/privacypolicy.html
  pages/termsofservice.html
  trail.js
Labels: gssoc, level2

#533 Fixed The "Broke UI" of Dot-Box "Home Page" including Tile Overflow
  index.html
Labels: gssoc, level3

#531 Fixed the positioning of the Home button on FAQs page
  pages/FAQs.html
  styles/FAQs.css
Labels: gssoc, level1

#529 Adding Chatbot and home icon to every Page
  .vscode/settings.json
  assets/images/Designer.jpeg
  index.html
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level3

#541 The Feedback Thank You Pop Up is Aligned
  styles/mainstyle.css
Labels: gssoc, level1

#543 feat: Hide the Trail Effect in Mobile View
  index.html
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#544 Adding Chatbot and home icon to every Page
  assets/images/Home.jpeg
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level3

#535 Draw situation fixed
  js/board.js
  js/box.js
  js/game.js
Labels: gssoc, level3

#545 "Re-created" and "Enhanced" The Ui of Contributors Page
  pages/contributors.html
  styles/contributors.css
Labels: gssoc, level3

#539 Sound button added
  js/board.js
  js/game.js
  pages/game.html
Labels: gssoc, level2

#552 Enhanced the privacy page
  styles/privacypolicy.css
Labels: gssoc, level2

#557 Enhanced Game Intereface by Adding Tour Guide
  pages/game.html
Labels: gssoc, level3

#556 Fixed the lets go button
  index.html
Labels: gssoc, level1

#551 Adding Chatbot in the Home Page and setting other Pages
  .vscode/settings.json
  assets/images/Home.jpeg
  index.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level3

#564 Enhanced and Fixed the Ui of About us
  pages/about.html
  styles/about.css
Labels: gssoc, level2

#567 Restored Contributors Page: fully debugged
  pages/about.html
  pages/contributors.html
  styles/about.css
Labels: gssoc, level2

#568 Made "Game Interface Responsive" And Fixed "Tour Step" Bugs
  pages/game.html
  styles/game.style.css
Labels: gssoc, level3

#585 Fixed The Footer Links in Contributors Page
  pages/contributors.html
Labels: gssoc, level1

#578 Improved how-to-play page
  pages/about.html
  pages/howtoplay.html
  styles/mainstyle.css
Labels: gssoc, level2

#571 Added Dynamic copyright year in footer
  index.html
Labels: gssoc, level2

#593 Added a draggable form with enhanced style
  index.html
Labels: gssoc, level3

#589 Made About us page Responsive
  pages/about.html
Labels: gssoc, level2

#592 Added live draggable scoreboard
  js/game.js
  pages/game.html
Labels: gssoc, level3

#594 ✔️Resolved the Navigating Issues
  pages/contributors.html
Labels: gssoc, level2

#602 Added Vertical ScrollBar Across All Pages
  pages/about.html
  pages/contributors.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#603 Added Scroll to Top Button in Lengthy Pages
  pages/about.html
  pages/contributors.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#613 Added A New Tour Step guide Introducing Draggable Scoreboard
  pages/game.html
Labels: gssoc, level1

#610 ✔️Added Diagonal-Hovering Effect to Each Card!
  pages/contributors.html
Labels: gssoc, level2

#609 ✔️Styled "Terms Of Service" Page!
  pages/privacypolicy.html
  pages/termsofservice.html
  styles/termsofservice.css
Labels: gssoc, level2

#612 Enhance Ui of FAQs Page: Proper Alignments, FIx Accordian and Make it Responsive
  pages/FAQs.html
  styles/FAQs.css
Labels: gssoc, level2

#606 Enhanced the Licensing page
  styles/licensing.css
Labels: gssoc, level2

#616 Added the Favicon to The missing pages
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#617 Added the Back to Home Button and Make The Pages Responsive
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#618 UI enhacement and Font added
  index.html
Labels: gssoc, level2

#619 Added naming feature
  index.html
  js/game.js
  js/index.js
Labels: gssoc, level2

#623 added a 30s time block
  js/game.js
  pages/game.html
Labels: gssoc, level2

#622 Fixed The Broken UI of Home Page
  index.html
Labels: gssoc, level2

#626 Styled and Added Animation to the Scroll to Top Button Match to Website Design Theme
  pages/about.html
  pages/contributors.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#630 Redesigned the Trail Effect Match to the Website Theme
  index.html
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#635 Bugs Fixed
  js/game.js
  js/index.js
  pages/game.html
  styles/game.style.css
  styles/mainstyle.css
Labels: gssoc, level3

#639 ✔️Improved FAQ Section Of the Website !
  pages/FAQs.html
  styles/FAQs.css
Labels: gssoc, level2

#642 Corrected Contributors' Profile picture
  pages/contributors.html
Labels: gssoc, level2

#643 Corrected container width of license page
  pages/licensing.html
Labels: gssoc, level2

#640 Enhanced The Timer Functionality and Restore the Game Interface
  pages/game.html
Labels: gssoc, level2

#632 Added hamburger Menu to all the required pages
  js/navbar.js
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/howtoplay.html
  styles/FAQs.css
  styles/mainstyle.css
  styles/navbar.css
Labels: gssoc, level3

#644 Enhanced the How to Play page
  pages/howtoplay.html
  styles/howtoplay.css
Labels: gssoc, level2

#645 Fix Navigations and Back to Home Buttons Result in 404 Page Not Found Error
  pages/about.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
Labels: gssoc, level2

#649 Enhanced and Improved "Draggable Scoreboard Functionality" and Game interface
  pages/game.html
Labels: gssoc, level3

#654 Colors - Dynamic selection
  js/game.js
  js/index.js
  pages/game.html
  styles/game.style.css
  styles/mainstyle.css
Labels: gssoc, level3

#651 Preloader added
  index.html
  js/loader.js
  js/maingame.js
  js/validation.js
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
  styles/game.style.css
  styles/mainstyle.css
Labels: gssoc, level2

#659 Corrected footer visibility
  index.html
Labels: gssoc, level2

#662 enhanced the main page container background
  index.html
  styles/mainstyle.css
Labels: gssoc, level2

#660 Fixed Preloader Visibility Issue and Implemented Error Handling
  index.html
  js/loader.js
  pages/404.html
  pages/FAQs.html
  pages/about.html
  pages/contributors.html
  pages/game.html
  pages/howtoplay.html
  pages/licensing.html
  pages/privacypolicy.html
  pages/termsofservice.html
  styles/mainstyle.css
Labels: gssoc, level2
