Repository ChromeGaming/Dot-Box, pull requests merged in 2024-06, with the labels that each got.

#297 404 not found page added
  404.html
  img/404pic.png
Labels: enhancement, gssoc, level2

#309 Updated CONTRIBUTING_GUIDELINE.md
  .github/CONTRIBUTING_GUIDELINE.md
Labels: documentation, gssoc, level1

#339 Defined different themes more prominently
  index.html
  js/game.js
  style.css
Labels: gssoc, level2

#321 Added loader
  index.html
  js/game.js
  style.css
Labels: gssoc, Under Review, level2

#318 added feedback button
  index.html
Labels: gssoc, Under Review, level1

#357 Made the UI completely responsive across all devices
  index.html
  style.css
Labels: enhancement, gssoc, level1

#362 added instructions.html page for detailed instructions and made ui responsive for all devices
  index.html
  instructions.html
  style.css
Labels: gssoc, level2

#372 Added User Friendly Navbar issue #198
  index.html
  style.css
Labels: gssoc, level3

#364 Footer Style color
  style.css
Labels: gssoc, level2

#161 added timelimit for each player
  js/game.js
  style.css
Labels: gssoc, Under Review, level2

#363 Added rulebook
  instructions.html
  style.css
Labels: gssoc, Under Review, level1

#299 Bug fix by surojit
  favicon.ico
  game.html
  index.html
  js/box.js
  js/edge.js
  js/game.js
  js/index.js
  styles/default.style.css
  styles/game.style.css
  styles/index.style.css
Labels: gssoc, Under Review, level2

#401 fixed home page layout
  index.html
  style.css
  styles/index.style.css
Labels: gssoc, level3

#397 Fixed issue #389 : Instruction section
  instructions.html
  style.css
Labels: gssoc, level1

#407 Added proper navbar at top
  index.html
  js/index.js
  style.css
Labels: gssoc, level2

#414 Colour added to edges
  js/board.js
  js/box.js
  js/edge.js
  js/game.js
Labels: gssoc, level2

#415 added reset functionality
  index.html
Labels: gssoc, level2

#419 input validation
  index.html
  styles/index.style.css
Labels: gssoc, level2

#421 Added footer in the home page
  index.html
  styles/index.style.css
Labels: gssoc, level2

#429 Added Emoji section
  assets/emoji-1.png
  assets/emoji-2.png
  assets/emoji-3.png
  assets/emoji-4.png
  assets/emoji-5.png
  emoji.js
  index.html
Labels: gssoc, level2

#426 Made Game to start in new page
  index.html
Labels: gssoc, level1

#423 fixed reset button issue no #428
  js/index.js
Labels: gssoc, level2

#431 Added "How to Play", "Terms of Service", and "Privacy Policy" Pages
  assets/Dot Box Tutorial.mp4
  howtoplay.html
  index.html
  instructions.html
  privacypolicy.html
  style.css
  termsofservice.html
Labels: gssoc, level3

#434 Fixed Contributors page, HowtoPlay page and Fixed Homepage Buttons UI
  README.md
  contributors.html
  howtoplay.html
  index.html
  styles/index.style.css
Labels: gssoc, level3
