Repository ChromeGaming/Dot-Box, pull requests merged in 2024-05, with the labels that each got.

#133 [Enhancement]: adding back ground color and font color #2
  back.mp4
  index.html
  style.css
Labels: enhancement, gssoc, level2

#114 Updated Documentation under issue #87 GGSOC 24
  README.md
Labels: gssoc

#172 Changed the labels and placeholder
  index.html
  style.css
Labels: gssoc, level1

#228 Update the documentation to show that all PRs opened for GSSOC should point to the develop branch
  README.md
  Screenshot 2024-05-21 202707.png
  Screenshot 2024-05-21 204528.png
  Screenshot 2024-05-21 205520.png
Labels: documentation, gssoc, level1

#226 [New Feature]: Would u like to add preloader?
  index.html
Labels: gssoc, level2

#84 Fixed responsiveness issue. #1
  style.css
Labels: gssoc, level1

#234 Update README.md
  README.md
Labels: gssoc, level1

#235 Create LEARN.md
  LEARN.md
Labels: gssoc, level1

#120 Replaced placeholders
  index.html
  style.css
Labels: gssoc, level2

#81 fix:removes colon
  index.html
Labels: gssoc, level1

#100 #15 Enhanced the connectivity with the webpage by incorporating links of social media platforms.
  index.html
  sticky sidebar/styles/style.css
  sticky sidebar/styles/style.css.map
  sticky sidebar/styles/style.scss
Labels: enhancement, gssoc, level2

#119 BG colour improved
  style.css
Labels: enhancement, gssoc, level1

#121 added the footer
  index.html
  style.css
Labels: enhancement, gssoc, level2

#126 added dark mode
  index.html
  js/dark.js
  style.css
Labels: gssoc, level2

#138 Solving Issue #53: Added Exit Button and Resolved Row and Column Size
  js/game.js
  style.css
Labels: enhancement, gssoc, level2

#139 Added players' name functionality
  index.html
  js/game.js
  style.css
Labels: enhancement, gssoc, level2

#181 Form Validation
  style.css
Labels: bug, gssoc, level1

#273 [Feature] : User cliked Indicates color
  js/box.js
  js/edge.js
  package-lock.json
  style.css
Labels: enhancement, gssoc, level1
